Repository Covengers-Pokedex/poke-sensei, pull requests merged in 2024-11, with the labels that each got.

#33 Feature - 포켓몬 한글 - 영문 이름 매핑 파일 생성 및 코드 리팩토링
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/pokemonModal/PokemonModal.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/constants/queryKeys.ts
  src/db/pokemonNamesKoEn.json
  src/hooks/useHidden.ts
  src/hooks/usePokemonList.ts
Labels: refactor, feat

#32 Feature: 전역에서 컴포넌트 없이 함수 호출만으로 사용할 수 있는 토스트 팝업 구현
  src/app/_components/Providers.tsx
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/modal/Portal.tsx
  src/app/_components/toast/Toast.tsx
  src/app/_components/toast/ToastList.tsx
  src/app/layout.tsx
  src/images/icons/icon-error.svg
  src/images/icons/icon-success.svg
  src/images/icons/icon-warn.svg
  src/stores/actions/useToastAction.ts
  src/stores/useToastStore.ts
  src/styles/tailwind.css
  src/types/toast.ts
  tailwind.config.ts
Labels: feat

#29 Refactor: 타입별포켓몬호출 API 변동에 따른 리팩토링
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/_components/Providers.tsx
  src/app/_components/main/PokedexMain.tsx
  src/app/_components/main/PokemonList.tsx
  src/app/_components/main/SearchSection.tsx
  src/app/main/page.tsx
  src/constants/mappingTypeColor.ts
  src/hooks/useInfinityPokemons.ts
  src/hooks/useInfinityScroll.ts
  src/hooks/useInfinityTypePokemons.ts
  src/hooks/useSearchPokemon.ts
  src/utils/koreanTypeToColor.ts
  src/utils/matchTypeToColor.ts
Labels: refactor, feat, fix

#38 Feature: 메타데이터 활용하여 오픈 그래프 구현
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/public/favicon.ico
  src/app/public/og-image.png
Labels: feat

#41 Feature: 포켓몬 모달 구현
  src/app/_components/Providers.tsx
  src/app/_components/button/LanguageToggleButton.tsx
  src/app/_components/button/MyFavoriteButton.tsx
  src/app/_components/button/QuizButton.tsx
  src/app/_components/landing/LandingTitle.tsx
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/main/MainTitle.tsx
  src/app/_components/main/PokedexMain.tsx
  src/app/_components/main/PokemonList.tsx
  src/app/_components/main/SearchSection.tsx
  src/app/_components/pokemonModal/FavoriteModal.tsx
  src/app/_components/pokemonModal/PokemonModal.tsx
  src/app/_components/pokemonModal/components/FavoritePokemon.tsx
  src/app/_components/pokemonModal/components/ModalTabContent.tsx
  src/app/_components/pokemonModal/components/ModalTabMenu.tsx
  src/app/_components/pokemonModal/components/ModalTitle.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/constants/mappingTypeColor.ts
  src/constants/pokemonMaxId.ts
  src/hooks/useInfinityPokemons.ts
  src/hooks/useInfinityTypePokemons.ts
  src/images/items/pokemon-dex.png
  src/lib/api/api.ts
  src/lib/api/fetch.ts
  src/lib/api/getPokemonData.ts
  src/lib/api/type.ts
  src/stores/useLanguageStore.ts
  src/types/language.ts
  src/utils/koreanTypeToColor.ts
Labels: refactor, feat

#45 Feature: 포켓몬 즐겨찾기 로컬스토리지 연동
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/main/PokedexMain.tsx
  src/app/_components/main/PokemonList.tsx
  src/app/_components/pokemonModal/FavoriteModal.tsx
  src/app/_components/pokemonModal/PokemonModal.tsx
  src/app/_components/pokemonModal/components/FavoritePokemon.tsx
  src/app/_components/pokemonModal/components/ModalImage.tsx
  src/app/_components/pokemonModal/components/ModalTabContent.tsx
  src/app/_components/pokemonModal/components/ModalTitle.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/styles/tailwind.css
Labels: refactor, feat

#46 Featuer: 포케피커 호버링 및 추가 효과 및 드래거블 메뉴 스타일 수정
  package-lock.json
  package.json
  src/app/_components/draggableSearchMenu/DraggableMenu.tsx
  src/app/_components/draggableSearchMenu/MonsterBall.tsx
  src/app/_components/loading/RandomPokemon.tsx
  src/app/_components/main/PokePicker.tsx
  src/app/_components/toast/ToastList.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: refactor, feat

#48 Feature: 영문 검색 구현
  src/app/_components/main/SearchSection.tsx
  src/hooks/useSearchPokemon.ts
  src/types/filteredPokemon.ts
Labels: refactor, feat

#53 Refactor 포켓몬 상세 모달 캐러셀 기능 수정
  src/app/_components/pokemonModal/PokemonModal.tsx
  src/app/_components/pokemonModal/components/ModalImage.tsx
Labels: refactor

#54 #51 feat: 언어 변환에 따른 텍스트 상수화
  src/app/_components/draggableSearchMenu/MonsterBall.tsx
  src/app/_components/main/PokePicker.tsx
  src/constants/localeText.ts
Labels: refactor

#55 Feature: 한영 텍스트 상수화
  src/app/_components/button/LanguageToggleButton.tsx
  src/app/_components/landing/LandingTitle.tsx
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/pokemonModal/FavoriteModal.tsx
  src/app/_components/pokemonModal/components/ModalTabContent.tsx
  src/app/_components/pokemonModal/components/ModalTabMenu.tsx
  src/constants/localeText.ts
Labels: refactor, feat

#62 Fix: 포켓몬 모달 이로치 노출 이미지 딜레이 수정
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/pokemonModal/components/FavoritePokemon.tsx
  src/app/_components/pokemonModal/components/ModalImage.tsx
Labels: fix

#63 Fix: 포켓몬 진화단계 이미지 딜레이 수정
  src/app/_components/pokemonModal/components/ModalTabContent.tsx
Labels: fix

#65 refator: 검색 인풋 placeholder 상수화 및 모달 내부 문구 단축
  src/app/_components/main/SearchSection.tsx
  src/constants/localeText.ts
Labels: refactor

#67 Refactor: 로딩컴포넌트 수정
  src/app/_components/main/PokedexMain.tsx
  src/app/main/page.tsx
  src/hooks/useInfinityPokemons.ts
  src/hooks/useInfinityTypePokemons.ts
  src/hooks/useSearchPokemon.ts
Labels: refactor, fix
