Repository Covengers-Pokedex/poke-sensei, pull requests merged in 2024-10, with the labels that each got.

#8 Feature: 포켓몬 api 구현
  .gitignore
  src/lib/api/api.ts
  src/lib/api/fetch.ts
  src/lib/api/getPokemonData.ts
  src/lib/api/instance.ts
  src/lib/api/path.ts
  src/lib/api/type.ts
Labels: feat

#11 Feature: 모달 프레임 구현
  .eslintrc.json
  src/app/_components/draggableSearchMenu/DraggableMenuTrigger.tsx
  src/app/_components/draggableSearchMenu/MonsterBall.tsx
  src/app/_components/draggableSearchMenu/SearchMenuContainer.tsx
  src/app/_components/draggableSearchMenu/SearchMenuContent.tsx
  src/app/_components/modal/BackDrop.tsx
  src/app/_components/modal/ModalFrame.tsx
  src/app/_components/modal/Portal.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/hooks/useHidden.ts
  src/hooks/useToggle.ts
  src/styles/tailwind.css
Labels: refactor, feat

#13 Feature: 랜딩페이지 구현
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/lib/api/api.ts
  src/lib/api/getPokemonData.ts
  src/styles/tailwind.css
  tailwind.config.ts
Labels: feat

#12 Feature: 포켓몬 리스트 무한스크롤 및 타입별 색상 매치
  src/app/_components/Providers.tsx
  src/app/_components/main/PokemonList.tsx
  src/app/_components/main/SearchSection.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/hooks/useInfinityScroll.ts
  src/lib/api/api.ts
  src/lib/api/type.ts
  src/utils/getQueryClient.ts
  src/utils/matchTypeToColor.ts
Labels: feat

#20 Feature: 타입 버튼, 타입 버튼 초기화 버튼 디자인 구현
  .vscode/settings.json
  src/app/_components/main/PokemonList.tsx
  src/app/_components/main/SearchSection.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/hooks/usePokemonList.ts
  src/lib/api/api.ts
  src/utils/convertHexToRGBA.ts
Labels: feat, design

#18 Feature: 타입에 관련된 포켓몬 리스트 api구현
  src/lib/api/api.ts
  src/lib/api/fetch.ts
  src/lib/api/getPokemonData.ts
  src/lib/api/path.ts
  src/lib/api/type.ts
Labels: feat

#21 Feature: 포켓몬 상세 모달 구현
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/pokemonModal/PokemonModal.tsx
  src/lib/api/api.ts
  src/lib/api/type.ts
  src/styles/tailwind.css
Labels: feat

#19 Refactor: HTML 구조적 타당성을 고려하여 Portal을 활용하는 것으로 변경 및 스타일 조정
  src/app/_components/draggableSearchMenu/DraggableMenuTrigger.tsx
  src/app/_components/draggableSearchMenu/MonsterBall.tsx
  src/app/_components/draggableSearchMenu/SearchMenuContainer.tsx
  src/app/_components/modal/BackDrop.tsx
  src/app/_components/modal/ModalFrame.tsx
  src/app/_components/modal/Portal.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: refactor, feat

#23 Feature: Loading 컴포넌트 제작
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/loading/RandomPokemon.tsx
  src/app/_components/loading/RandomPokemonLoading.tsx
  src/app/_components/main/PokemonList.tsx
  src/app/_components/modal/Portal.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/hooks/usePokemonList.ts
  src/lib/api/api.ts
Labels: feat

#24 Feature: 포켓몬 진화단계 api 구현
  src/app/_components/landing/PokemonQuiz.tsx
  src/app/_components/pokemonModal/PokemonModal.tsx
  src/app/_components/pokemonModal/components/ModalImage.tsx
  src/app/_components/pokemonModal/components/ModalTabContent.tsx
  src/app/_components/pokemonModal/components/ModalTabMenu.tsx
  src/app/_components/pokemonModal/components/ModalTitle.tsx
  src/images/items/monster-ball.png
  src/lib/api/api.ts
  src/lib/api/fetch.ts
  src/lib/api/getPokemonData.ts
  src/lib/api/type.ts
  src/styles/tailwind.css
  src/utils/randomNumber.ts
Labels: refactor, feat
